# Generated by Django 2.0.1 on 2018-01-08 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdriveApp', '0002_fileuploads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileuploads',
            name='file_name',
            field=models.FileField(upload_to='uploads/%Y/%m/%d'),
        ),
    ]
