# Generated by Django 2.0.1 on 2018-01-08 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdriveApp', '0004_auto_20180108_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileuploads',
            name='file_name',
            field=models.FileField(upload_to=''),
        ),
    ]
